# Generated by Django 3.2.18 on 2023-05-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230502_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tea',
            options={'ordering': ['-created_at'], 'verbose_name': 'Çay', 'verbose_name_plural': 'Çaylar'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'İstifadəçi', 'verbose_name_plural': 'İstifadəçilər'},
        ),
        migrations.AddField(
            model_name='tea',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Çəkisi'),
        ),
    ]
