# Generated by Django 3.2.18 on 2023-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tea_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıqlama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Qiyməti')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mövcuddur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('stock_quantity', models.IntegerField(blank=True, null=True, verbose_name='Stok sayı')),
            ],
        ),
    ]
